#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# Important - set the type for the functions to know what's going on
TYPE=provision

# Checks the vars are set before running
source functions

#clean to start owfs
killOwfs

# Check and make the dirs
makeOutputDirs

# Start logging if true
if [ "$LOGGING" = true ]
then
    startLog
fi

# Set up the statefile
touch "$STATEFILE"

# Check USB device is connected
checkDevice

# Do the deed
provisionLogger

# end owfs
killOwfs

# Stop logging
if [ "$LOGGING" = true ]
then
    endLog
fi

cleanUp

exit
